### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/dxpr_satis#4]
A client reported to me the following:

_[14:12, 3/18/2021] Maurits: we get an error when running composer install (when not already installed). It gives a checksum error after the zip download, then tries to fetch it from git (which it can't because no credentials). I will send you the error later, now in a meeting
[14:12, 3/18/2021] Maurits: the command for setting access token is still in place_

We will get the error message later but I'm not sure if you need the error message to reproduce this so I posted this without the message.

**Comment by jjroelofs** [comment]
@hoatle apparently there are quite a few reports about this type of error:

https://www.google.com/search?q=satis+checksum+error

**Comment by hoatle** [comment]
related:
- https://github.com/dxpr/dxpr_satis/commit/1ee728b56969038ba970d3a8c3c71105eddd35dd
- https://github.com/composer/satis/issues/516#issuecomment-686360314

**Comment by hoatle** [comment]
workaround for the error:

```
you can run "composer update mirrors" to fix the checksums in the lock, however, this might require the removal of the "/vendor" dir and "composer.lock" file.
```

The error is fixed now: the uploaded distribution files will not be re-updated (re-archived).

Steps to reproduce the error:
- run `composer install`
- execute satis build
- run `composer install` again

**Comment by jjroelofs** [comment]
@hoatle should I just tell the client the problem is fixed and he should try again, or does the client need to take prerequisite steps, like removing his package lock file, or clearing some caches, or removing dxpr_builder and re-adding it?

Thx

**Comment by hoatle** [comment]
yes, he should try to composer install from scratch and then everything
should be ok

**Comment by jjroelofs** [comment]
What does "from scratch" mean? He uses the product in a website that is very complicated and expensive to build and maintain, I'm sure you don't mean he needs to delete all the files in the project?

**Comment by hoatle** [comment]
@jjroelofs he should try this:
- execute `$ composer update mirrors` and `$ composer install` to see if the problem is fixed
- if not fixed yet, he could try to delete `/vendor` dir and `composer.lock` file and `$ composer install`

next time, `$ composer install` should work.

**Comment by jjroelofs** [comment]
Thx, I'll leave this open until the client confirms it's working OK

**Comment by jjroelofs** [comment]
thx works for the client!
