### ISSUE TITLE
composer.json caching issues causing releases to be unavailable to seemingly random requesters

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/dxpr_satis#5]
This Friday, even though I always repeat "Never release on friday", I ignored my own advice and of course it turned out to be a bad decision. 

While the release worked fine on my laptop, the new version was not available to composer on the try.dxpr.com server. Various other team members got different results trying to "composer require dxpr/dxpr_builder:1.4.1" or the beta1 and beta2 releases for 1.4.1.

After a lot of research (On Saturday of course) I discovered we had a caching issue: CloudFront was serving older versions of our Satis files on S3. The different versions of the file served to different machines can be explained by the different machines connecting to different AWS locations/servers, or by having different request headers (Accept headers).

## Workaround

As a workaround I cleared the entire CloudFront cache:
![image](https://user-images.githubusercontent.com/904576/113477698-fe1ef380-9483-11eb-9fda-bcfc6b0de735.png)

This solved the most urgent problem.

## Makeshift solution

![image](https://user-images.githubusercontent.com/904576/113477743-5a821300-9484-11eb-8f56-f8457d3be4ea.png)

As a makeshift solution I manually set No-Cache headers on the dxpr_builder.json and dxpr_builder_e.json files Steps to reproduce:

https://drive.google.com/file/d/1CzCxVJ7vHOIL3F2Z0SmLCvwtRaRYz0AY/view

However, I am not sure if this is a permanent solution because these files are generated by Satis

## Permanent Solution

@hoatle Please see if you can find a permanent solution. Can you tell why this happened in the first place? Does Satis not set Cache-control headers on its own? If it does why are they ignored by S3 or CloudFront?

My understanding is that the default CloudFront cache time is 24 hours. That is more than fine for our zip files, but not for the json files.

**Comment by hoatle** [comment]
cache invalidation is fixed now

**Comment by jjroelofs** [comment]
thx!
